### ISSUE TITLE
My confusion on different basis sets involved in one lobster computation.

### ISSUE THREAD

**Issue by hongyi-zhao** [JaGeo/LobsterPy#304]
According to the description [here](https://jageo.github.io/LobsterPy/tutorial/commandlineinterface.html#creating-input-files):

> For example if Cd element has two basis sets, aka, `4d 5s` and `4d 5s 5p`, thus following files are created:
> ```
> INCAR.lobsterpy-0
> INCAR.lobsterpy-1
> lobsterin.lobsterpy-0
> lobsterin.lobsterpy-1
> ```

I have the following confusion:

1. Is the number of these basis sets unrelated to the type of POTCAR used? For example, for the `Cd` element, the following `POTCAR`s are available:
```
$ ls ~/Public/hpc/vasp/pot/potcar/POT_PAW_PBE_64/Cd* -R
/home/werner/Public/hpc/vasp/pot/potcar/POT_PAW_PBE_64/Cd:
POTCAR  PSCTR

/home/werner/Public/hpc/vasp/pot/potcar/POT_PAW_PBE_64/Cd_GW:
POTCAR  PSCTR

/home/werner/Public/hpc/vasp/pot/potcar/POT_PAW_PBE_64/Cd_sv_GW:
POTCAR  PSCTR
```

2. In a specific study, should I choose which basis set for calculation and analysis, or do I have to perform calculations and analyses on all of them?
3. Is the current implementation of lobster applicable to all `POTCAR` types of the latest version of vasp? For example, those I listed above.

Regards,
Zhao

**Comment by hongyi-zhao** [comment]
For question 3 above, I tried the following method, and it seems that pymatgen does not fully support it so far:

```python
$ cat create_and_test_potcar.py 
from pymatgen.io.vasp.inputs import Potcar, PotcarSingle
import os

# Specify the required elements
potcar_symbols = ["Cd_GW", "F"]

# Specify the POTCAR functional
functional = "PBE_64"  # Ensure using the correct functional set

# Print the POTCAR file path for each element
for symbol in potcar_symbols:
    try:
        # Create PotcarSingle object for the symbol and functional
        potcar_single = PotcarSingle.from_symbol_and_functional(symbol, functional)
        if potcar_single:
            functional_dir_dict = potcar_single.functional_dir
            if functional in functional_dir_dict:
                functional_dir = functional_dir_dict[functional]
                potcar_path = os.path.join(functional_dir, symbol, "POTCAR")
                print(f"{symbol} POTCAR created successfully.")
                print(f"Element: {potcar_single.element}")
                print(f"Symbol: {potcar_single.symbol}")
                print(f"Functional: {potcar_single.functional}")
                print(f"Number of electrons: {potcar_single.nelectrons}")
                print(f"Potential type: {potcar_single.potential_type}")
                print(f"POTCAR file path: {potcar_path}")
            else:
                print(f"Functional {functional} not found in directory dictionary.")
        else:
            print(f"POTCAR file for {symbol} with functional {functional} not found.")
    except Exception as e:
        print(f"Error occurred for symbol {symbol}: {e}")

# Create Potcar object
try:
    potcar = Potcar(potcar_symbols, functional)
    # Write the Potcar to a file
    potcar.write_file("POTCAR")
    # Read the generated POTCAR file
    potcar_read = Potcar.from_file("POTCAR")
    # Print POTCAR information
    # print(potcar_read)
except Exception as e:
    print(f"Error occurred while creating or reading POTCAR: {e}")
```
```shell
$ python create_and_test_potcar.py 
Cd_GW POTCAR created successfully.
Element: Cd
Symbol: Cd_GW
Functional: PBE
Number of electrons: 12.0
Potential type: PAW
POTCAR file path: POT_PAW_PBE_64/Cd_GW/POTCAR
F POTCAR created successfully.
Element: F
Symbol: F
Functional: PBE
Number of electrons: 7.0
Potential type: PAW
POTCAR file path: POT_PAW_PBE_64/F/POTCAR

$ lobsterpy create-inputs --overwrite
/home/werner/Public/repo/github.com/materialsproject/pymatgen.git/pymatgen/io/lobster/inputs.py:642: UserWarning: These POTCARs are not compatible with Lobster up to version 4.1.0.
 The keywords SHA256 and COPYR cannot be handled by Lobster 
 and will lead to wrong results.
  warnings.warn(
Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/datasci/bin/lobsterpy", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/werner/Public/repo/github.com/JaGeo/LobsterPy.git/lobsterpy/cli.py", line 33, in main
    run(args)
  File "/home/werner/Public/repo/github.com/JaGeo/LobsterPy.git/lobsterpy/cli.py", line 987, in run
    list_basis_dict = Lobsterin.get_all_possible_basis_functions(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/Public/repo/github.com/materialsproject/pymatgen.git/pymatgen/io/lobster/inputs.py", line 401, in get_all_possible_basis_functions
    max_basis = Lobsterin.get_basis(
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/Public/repo/github.com/materialsproject/pymatgen.git/pymatgen/io/lobster/inputs.py", line 376, in get_basis
    raise ValueError(
ValueError: Missing basis information for POTCAR symbol: Cd_GW. Please provide the basis manually.

```

**Comment by JaGeo** [comment]
These basis sets have been developed for the PBE_54 POTCARs.

**Comment by hongyi-zhao** [comment]
> These basis sets have been developed for the PBE_54 POTCARs.

Therefore, this should be a feature of pymatgen that has not yet been implemented and needs to be enhanced.

**Comment by JaGeo** [comment]
@hongyi-zhao For this, you need to check the LOBSTER manual or LOBSTER itself.

**Comment by JaGeo** [comment]
If you are interested in running LOBSTER with newer basis sets and want some more information on this, please feel free to write me an email and then we can talk about a collaboration.

**Comment by hongyi-zhao** [comment]
> @hongyi-zhao For this, you need to check the LOBSTER manual or LOBSTER itself.

I checked the release notes of the latest version of lobster-5.1.0 and did not find any information regarding whether it supports the latest version of VASP POTCAR. Therefore, this should be further discussed and confirmed with the lobster development team.

**Comment by hongyi-zhao** [comment]
> If you are interested in running LOBSTER with newer POTCARs and want some more information on this and how the code here and in pymatgen works, please feel free to write me an email and then we can talk about a collaboration.

In my group, there are also several graduate students and researchers conducting collaborative research. We can communicate appropriately to see if there is an opportunity to arrange further research work.

**Comment by JaGeo** [comment]
As said, we support PBE_54 and only the standard POTCARs used in the LOBSTER input set in pymatgen. We can surely document this more clearly.

**Comment by hongyi-zhao** [comment]
Agreed.

**Comment by JaGeo** [comment]
You can check out the yaml files here: https://github.com/materialsproject/pymatgen/tree/master/pymatgen/io/lobster/lobster_basis

**Comment by hongyi-zhao** [comment]
I have noticed these files.

**Comment by JaGeo** [comment]
I realized I haven't answered your 2nd question fully:
- you really need to test
- for semi-conductors, we have successfully used the smallest possible basis set but this might not be sufficient for metals (https://www.nature.com/articles/s41597-023-02477-5)
- this is, however, a topic we are still working on as well

**Comment by JaGeo** [comment]
Closing this as well
